model:
  name: fcidump
  params:
    model_path: /home/hzhangxyz/qmp-models/Fe2S2_30_40.FCIDUMP.gz
    ref_energy: 0

network:
  name: mlp/u1u1
  params:
    hidden: [512, 512]

optimizer:
  name: Adam
  params:
    lr: 0.001

common:
  random_seed: 2333
  master_port: 23342
  devices:
    - cuda:3
    - cuda:4
    - cuda:5
  dtype: bfloat16

action:
  name: haar
  params:
    sampling_count_from_neural_network: 102400
    sampling_count_from_last_iteration: 102400
    krylov_extend_count: 10240
    krylov_period: 32
    krylov_iteration: 32
    krylov_extend_first: true
